/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//TELA PRONTA
package VISUAL;

import CONTROLE.CFabricante;
import CONTROLE.CFornecedor;
import CONTROLE.CMercadoria;
import CONTROLE.CTabela;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
//atualizado

/**
 *
 * @author jose
 */
public class TelaMercadoriaCadastro extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroProduto
     */
    CTabela cTabela;
    CMercadoria cMercadoria;
    CFornecedor cFornecedor;
    CFabricante cFabricante;

    public TelaMercadoriaCadastro() {
        initComponents();
        cTabela = new CTabela();
        cTabela.tabela.setTipo(2);
        cMercadoria = new CMercadoria();
        cFornecedor = new CFornecedor();
        cFabricante = new CFabricante();
        if ("Administrativo".equals(TelaLogin.tipoUsuario)) {
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
        } else if ("Comum".equals(TelaLogin.tipoUsuario)) {
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
        } else {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCancelar = new javax.swing.JButton();
        btnCadMerc = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtCadMerFab = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCadMerVal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCadMerMod = new javax.swing.JTextField();
        txtCadMerFor = new javax.swing.JTextField();
        txtCadMerMar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomMer = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbBusca = new javax.swing.JTable();
        cbPesquisar = new javax.swing.JComboBox<String>();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCadMerc.setText("Cadastrar");
        btnCadMerc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadMercActionPerformed(evt);
            }
        });

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel4.setPreferredSize(new java.awt.Dimension(357, 300));

        txtCadMerFab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCadMerFabKeyReleased(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel8.setText("*Valor custo:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("*Modelo:");

        txtCadMerVal.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtCadMerVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadMerValActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText("*Marca:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setText("*Fornecedor:");

        jLabel1.setText("*Fabricante:");

        txtCadMerFor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCadMerForKeyReleased(evt);
            }
        });

        jLabel2.setText("*Nome:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(jLabel1))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel5)))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCadMerFab, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(txtCadMerFor)
                            .addComponent(txtCadMerMar)
                            .addComponent(txtCadMerMod)
                            .addComponent(txtNomMer)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCadMerVal, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNomMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCadMerFab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCadMerFor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCadMerMar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCadMerMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCadMerVal, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );

        tbBusca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Data", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBusca.setEditingColumn(0);
        tbBusca.setEditingRow(0);
        tbBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBuscaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbBusca);

        cbPesquisar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "COD_MERCADORIA", "Nome", "NascData", "Telefone" }));
        cbPesquisar.setToolTipText("");
        cbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPesquisarActionPerformed(evt);
            }
        });

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        btnPesquisar.setText("Limpar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(cbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 533, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnCadMerc, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadMerc)
                    .addComponent(btnCancelar)
                    .addComponent(btnExcluir)
                    .addComponent(btnAlterar))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCadMercActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadMercActionPerformed
        // TODO add your handling code here:
        cMercadoria.mercadoria.setNome(txtNomMer.getText());
        cMercadoria.mercadoria.setCodFabricante(cFabricante.fabricante.getCod());
        cMercadoria.mercadoria.setCodFornecedor(cFornecedor.fornecedor.getCod());
        cMercadoria.mercadoria.setMarca(txtCadMerMar.getText());
        cMercadoria.mercadoria.setModelo(txtCadMerMod.getText());
        cMercadoria.mercadoria.setValorCustoMercadoria(Float.parseFloat(txtCadMerVal.getText()));
        JOptionPane.showMessageDialog(null, cMercadoria.gravar(cMercadoria.mercadoria));
    }//GEN-LAST:event_btnCadMercActionPerformed

    private void tbBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBuscaMouseClicked
        // TODO add your handling code here:
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
        switch (cTabela.tabela.getTipo()) {
            case 1:
                Object t = tbBusca.getValueAt(tbBusca.getSelectedRow(), 1);
                Object d = tbBusca.getValueAt(tbBusca.getSelectedRow(), 0);
                txtCadMerFab.setText((String) t);
                cFabricante.fabricante.setCod((int) d);
                cFabricante.buscar(cFabricante.fabricante);
                break;
            case 2:
                cTabela.tabela.setLin(tbBusca.getSelectedRow());
                int i = Integer.parseInt((tbBusca.getModel()).getValueAt(cTabela.tabela.getLin(), 0).toString());
                cTabela.tabela.setCod(i);
                boolean result;
                cMercadoria.mercadoria.setCod(cTabela.tabela.getCod());
                result = cMercadoria.buscar(cMercadoria.mercadoria);

                //JOptionPane.showMessageDialog(null, result);
                if (result) {
                    cFabricante.fabricante.setCod(cMercadoria.mercadoria.getCodFabricante());
                    cFabricante.buscar(cFabricante.fabricante);
                    cFornecedor.fornecedor.setCod(cMercadoria.mercadoria.getCodFornecedor());
                    cFornecedor.buscar(cFornecedor.fornecedor);
                    //  txtCadCod.setText(Integer.toString(cMercadoria.mercadoria.getCod()));
                    txtCadMerFab.setText(cFabricante.fabricante.getNome());
                    txtCadMerFor.setText(cFornecedor.fornecedor.getNome());
                    //JOptionPane.showMessageDialog(null,cMercadoria.mercadoria.getTelefone());
                    txtCadMerMar.setText(cMercadoria.mercadoria.getMarca());
                    txtCadMerMod.setText(cMercadoria.mercadoria.getModelo());
                    txtNomMer.setText(cMercadoria.mercadoria.getNome());
                    txtCadMerVal.setText(Float.toString(cMercadoria.mercadoria.getValorCustoMercadoria()));
                }
                break;

            case 3:
                Object a = tbBusca.getValueAt(tbBusca.getSelectedRow(), 1);
                Object b = tbBusca.getValueAt(tbBusca.getSelectedRow(), 0);
                txtCadMerFor.setText((String) a);
                cFornecedor.fornecedor.setCod((int) b);
                cFornecedor.buscar(cFornecedor.fornecedor);
                break;
            default:
                break;
        }
    }//GEN-LAST:event_tbBuscaMouseClicked

    private void cbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPesquisarActionPerformed

    private void txtPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarKeyPressed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        // TODO add your handling code here:
        tbBusca.setModel(DbUtils.resultSetToTableModel(cTabela.pesqMer("tbmercadoria", txtPesquisar.getText(), String.valueOf(cbPesquisar.getSelectedItem()))));
        tbBusca.getColumnModel().getColumn(0).setPreferredWidth(75);
        tbBusca.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(3).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(4).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(5).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(6).setPreferredWidth(150);
        tbBusca.setAutoCreateRowSorter(true);
        cTabela.tabela.setTipo(2);
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        cMercadoria.mercadoria.setCod(0);
        cMercadoria.mercadoria.setCodFabricante(0);
        cMercadoria.mercadoria.setCodFornecedor(0);
        cFabricante.fabricante.setCod(0);
        cFornecedor.fornecedor.setCod(0);
        txtCadMerFab.setText("");
        txtCadMerFor.setText("");
        txtCadMerMar.setText("");
        txtCadMerMod.setText("");
        txtNomMer.setText("");
        txtCadMerVal.setText("");
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtCadMerValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadMerValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadMerValActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, cMercadoria.apagar(cMercadoria.mercadoria));
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        cMercadoria.mercadoria.setNome(txtNomMer.getText());
        cMercadoria.mercadoria.setCodFabricante(cFabricante.fabricante.getCod());
        cMercadoria.mercadoria.setCodFornecedor(cFornecedor.fornecedor.getCod());
        cMercadoria.mercadoria.setMarca(txtCadMerMar.getText());
        cMercadoria.mercadoria.setModelo(txtCadMerMod.getText());
        cMercadoria.mercadoria.setValorCustoMercadoria(Float.parseFloat(txtCadMerVal.getText()));
        JOptionPane.showMessageDialog(null, cMercadoria.alterar(cMercadoria.mercadoria));
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtCadMerFabKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadMerFabKeyReleased
        // TODO add your handling code here:
        tbBusca.setModel(DbUtils.resultSetToTableModel(cTabela.pesq("tbfabricante", txtCadMerFab.getText(), "NOME")));
        tbBusca.getColumnModel().getColumn(0).setPreferredWidth(75);
        tbBusca.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(3).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(4).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(5).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(6).setPreferredWidth(150);
        tbBusca.setAutoCreateRowSorter(true);
        cTabela.tabela.setTipo(1);
    }//GEN-LAST:event_txtCadMerFabKeyReleased

    private void txtCadMerForKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadMerForKeyReleased
        // TODO add your handling code here:
        tbBusca.setModel(DbUtils.resultSetToTableModel(cTabela.pesq("tbfornecedor", txtCadMerFor.getText(), "NOME")));
        tbBusca.getColumnModel().getColumn(0).setPreferredWidth(75);
        tbBusca.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(3).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(4).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(5).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(6).setPreferredWidth(150);
        tbBusca.setAutoCreateRowSorter(true);
        cTabela.tabela.setTipo(3);

    }//GEN-LAST:event_txtCadMerForKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadMerc;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cbPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JTable tbBusca;
    private javax.swing.JTextField txtCadMerFab;
    private javax.swing.JTextField txtCadMerFor;
    private javax.swing.JTextField txtCadMerMar;
    private javax.swing.JTextField txtCadMerMod;
    private javax.swing.JTextField txtCadMerVal;
    private javax.swing.JTextField txtNomMer;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
