/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//TELA PRONTA
package VISUAL;

import CONTROLE.CFuncionario;
import CONTROLE.CTabela;
import CONTROLE.CValidacao;
import CONTROLE.CWebServiceCep;
import MODELO.Validacao;
import static VISUAL.TelaFuncionarioCadastro.tbBusca;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
//atualizado

/**
 *
 * @author jose
 */
public class TelaFuncionarioCadastro extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cadastro
     */
    CValidacao cvalidacao;
    CFuncionario cFuncionario;
    CTabela cTabela;
    private int cod;
    private int lin;

    public TelaFuncionarioCadastro() {
        initComponents();
        cTabela = new CTabela();
        cvalidacao = new CValidacao();
        cFuncionario = new CFuncionario();
        if ("Administrativo".equals(TelaLogin.tipoUsuario)) {
            btnAlterar.setEnabled(false);
            btnDadExcluir1.setEnabled(false);
        } else if ("Comum".equals(TelaLogin.tipoUsuario)) {
            btnAlterar.setEnabled(false);
            btnDadExcluir1.setEnabled(false);
        } else {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        txtCadFunNom = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCadFunEma = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCadFunCpf = new javax.swing.JFormattedTextField();
        txtCadFunRg = new javax.swing.JFormattedTextField();
        txtCadFunCel = new javax.swing.JFormattedTextField();
        txtCadFunTel = new javax.swing.JFormattedTextField();
        txtCadFunDat = new javax.swing.JFormattedTextField();
        jPanel5 = new javax.swing.JPanel();
        txtCadFunRua = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCadFunCid = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtCadFunBai = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtCadFunNum = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCadFunCom = new javax.swing.JTextArea();
        txtCadFunCep = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cbCadFunUf = new javax.swing.JComboBox<String>();
        btnCadCancelar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        cbPesquisar = new javax.swing.JComboBox<String>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbBusca = new javax.swing.JTable();
        btnDadExcluir1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(841, 710));

        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel4.setPreferredSize(new java.awt.Dimension(357, 300));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel8.setText("Email");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel3.setText("CPF");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel4.setText("Celular");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel5.setText("Telefone");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel6.setText("Data Nasc.:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel7.setText("RG");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel2.setText("Nome ");

        try {
            txtCadFunCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadFunCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFunCpfActionPerformed(evt);
            }
        });

        try {
            txtCadFunRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCadFunCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) 9####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCadFunTel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            txtCadFunDat.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCadFunEma)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCadFunDat, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCadFunCel, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(txtCadFunCpf)
                            .addComponent(txtCadFunRg)
                            .addComponent(txtCadFunTel))
                        .addGap(0, 95, Short.MAX_VALUE))
                    .addComponent(txtCadFunNom))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCadFunNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtCadFunDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtCadFunTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCadFunCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCadFunCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCadFunRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCadFunEma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        jPanel5.setPreferredSize(new java.awt.Dimension(357, 315));

        jLabel12.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel12.setText("Cidade");

        jLabel13.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel13.setText("Bairro");

        jLabel16.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel16.setText("Rua");

        txtCadFunNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFunNumActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel17.setText("Nº");

        jLabel11.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel11.setText("Complemento");

        txtCadFunCom.setColumns(20);
        txtCadFunCom.setLineWrap(true);
        txtCadFunCom.setRows(5);
        jScrollPane1.setViewportView(txtCadFunCom);

        try {
            txtCadFunCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCadFunCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadFunCepActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jLabel14.setText("CEP");

        jLabel9.setText("UF");

        cbCadFunUf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbCadFunUf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCadFunUfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCadFunBai, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCadFunRua, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel5Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCadFunCep, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel17)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCadFunNum, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCadFunCid)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbCadFunUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadFunCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel17)
                    .addComponent(txtCadFunNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadFunRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadFunBai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtCadFunCid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbCadFunUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        btnCadCancelar.setText("Cancelar");
        btnCadCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadCancelarActionPerformed(evt);
            }
        });

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
        });
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        btnPesquisar.setText("Limpar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        cbPesquisar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "COD_FUNCIONARIO", "Nome", "NascData", "Telefone" }));
        cbPesquisar.setToolTipText("");
        cbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPesquisarActionPerformed(evt);
            }
        });

        tbBusca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Data", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBusca.setEditingColumn(0);
        tbBusca.setEditingRow(0);
        tbBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBuscaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbBusca);

        btnDadExcluir1.setText("Excluir");
        btnDadExcluir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDadExcluir1MouseClicked(evt);
            }
        });
        btnDadExcluir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDadExcluir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDadExcluir1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(btnCadCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisar)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCadastrar)
                    .addComponent(btnAlterar)
                    .addComponent(btnCadCancelar)
                    .addComponent(btnDadExcluir1))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCadFunCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFunCepActionPerformed

        CWebServiceCep cWeb = new CWebServiceCep();
        //A ferramenta de busca ignora qualquer caracter que n?o seja n?mero.
        //caso a busca ocorra bem, imprime os resultados.
        cWeb.webServiceCep = cWeb.webServiceCep.searchCep(txtCadFunCep.getText());
        if (cWeb.webServiceCep.wasSuccessful()) {
            txtCadFunRua.setText(cWeb.webServiceCep.getLogradouroFull());
            txtCadFunCid.setText(cWeb.webServiceCep.getCidade());
            txtCadFunBai.setText(cWeb.webServiceCep.getBairro());
            cbCadFunUf.setSelectedItem(cWeb.webServiceCep.getUf());
            //caso haja problemas imprime as exce??es.
        } else {
            JOptionPane.showMessageDialog(null, "Erro numero: " + cWeb.webServiceCep.getResulCode());

            JOptionPane.showMessageDialog(null, "Descrição do erro: " + cWeb.webServiceCep.getResultText());
        }
    }//GEN-LAST:event_txtCadFunCepActionPerformed

    private void cbCadFunUfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCadFunUfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCadFunUfActionPerformed

    private void btnCadCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCadCancelarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        cFuncionario.funcionario.setNome(txtCadFunNom.getText());
        cFuncionario.funcionario.setDataNasc((txtCadFunDat.getText()).replace("/", "-"));
        cFuncionario.funcionario.setTelefone(cFuncionario.funcionario.retiraCel(txtCadFunTel.getText()));
        cFuncionario.funcionario.setCelular(cFuncionario.funcionario.retiraCel(txtCadFunCel.getText()));
        cFuncionario.funcionario.setCpf(cFuncionario.funcionario.retira(txtCadFunCpf.getText()));
        cFuncionario.funcionario.setRg(cFuncionario.funcionario.retira(txtCadFunRg.getText()));
        cFuncionario.funcionario.setEmail(txtCadFunEma.getText());
        cFuncionario.funcionario.setCep(cFuncionario.funcionario.retira(txtCadFunCep.getText()));
        cFuncionario.funcionario.setRua(txtCadFunRua.getText());
        cFuncionario.funcionario.setNumero(Integer.parseInt(txtCadFunNum.getText()));
        cFuncionario.funcionario.setBairro(txtCadFunBai.getText());
        cFuncionario.funcionario.setCidade(txtCadFunCid.getText());
        cFuncionario.funcionario.setComplemento(txtCadFunCom.getText());
        cFuncionario.funcionario.setEstado(cbCadFunUf.getItemAt(cbCadFunUf.getSelectedIndex()));
        // cFuncionario.funcionario.setObservacao(txtCadFunFunObs.getText());
        if (Validacao.validaCpf(cFuncionario.funcionario.getCep())) {
            if (Validacao.validarEmail(cFuncionario.funcionario.getEmail()) > 0) {
                JOptionPane.showMessageDialog(null, cFuncionario.gravar(cFuncionario.funcionario));
            } else {
                JOptionPane.showMessageDialog(null, "Email não valido");
            }
        } else {
            JOptionPane.showMessageDialog(null, "CPF não valido");
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtCadFunCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFunCpfActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, cvalidacao.validaCpf(txtCadFunCpf.getText()));
        if (cvalidacao.validaCpf(txtCadFunCpf.getText())) {
            JOptionPane.showMessageDialog(null, "Valido");
        } else {
            JOptionPane.showMessageDialog(null, "Não valido");
        }
    }//GEN-LAST:event_txtCadFunCpfActionPerformed

    private void tbBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBuscaMouseClicked
        // TODO add your handling code here:
        btnAlterar.setEnabled(true);
        btnDadExcluir1.setEnabled(true);
        cTabela.tabela.setLin(tbBusca.getSelectedRow());
        int i = Integer.parseInt((tbBusca.getModel()).getValueAt(cTabela.tabela.getLin(), 0).toString());
        cTabela.tabela.setCod(i);
        boolean result;
        cFuncionario.funcionario.setCod(cTabela.tabela.getCod());
        result = cFuncionario.buscar(cFuncionario.funcionario);
        //JOptionPane.showMessageDialog(null, result);
        if (result) {
            //  txtCadFunCod.setText(Integer.toString(cFuncionario.funcionario.getCod()));
            txtCadFunNom.setText((cFuncionario.funcionario.getNome()));
            txtCadFunTel.setText(cFuncionario.funcionario.getTelefone());
            //JOptionPane.showMessageDialog(null,cFuncionario.funcionario.getTelefone());

            cFuncionario.funcionario.getDataNasc();
            String ano = cFuncionario.funcionario.getDataNasc().substring(0, 4);
            String mes = cFuncionario.funcionario.getDataNasc().substring(5, 7);
            String dia = cFuncionario.funcionario.getDataNasc().substring(8);
            cFuncionario.funcionario.setDataNasc(dia + "" + mes + "" + ano);
            txtCadFunDat.setText(cFuncionario.funcionario.getDataNasc());
            txtCadFunCel.setText(cFuncionario.funcionario.getCelular());
            txtCadFunCpf.setText(cFuncionario.funcionario.getCpf());
            txtCadFunRg.setText(cFuncionario.funcionario.getRg());
            txtCadFunEma.setText(cFuncionario.funcionario.getEmail());
            txtCadFunRua.setText(cFuncionario.funcionario.getRua());
            txtCadFunNum.setText(Integer.toString(cFuncionario.funcionario.getNumero()));
            txtCadFunCep.setText(cFuncionario.funcionario.getCep());
            txtCadFunBai.setText(cFuncionario.funcionario.getBairro());
            txtCadFunCid.setText(cFuncionario.funcionario.getCidade());
            txtCadFunCom.setText(cFuncionario.funcionario.getComplemento());
        }
    }//GEN-LAST:event_tbBuscaMouseClicked

    private void cbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPesquisarActionPerformed

    private void txtPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtPesquisarKeyPressed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, txtPesquisar.getText());
        String pr = (String) (txtPesquisar.getText());
        String op = (String) (cbPesquisar.getSelectedItem());
        String tb = "tbfuncionario";
        tbBusca.setModel(DbUtils.resultSetToTableModel(cTabela.pesq(tb, pr, op)));
        tbBusca.getColumnModel().getColumn(0).setPreferredWidth(75);
        tbBusca.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(3).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(4).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(5).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(6).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(7).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(8).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(9).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(10).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(11).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(12).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(13).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(14).setPreferredWidth(150);
        tbBusca.setAutoCreateRowSorter(true);
    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        btnAlterar.setEnabled(false);
        btnDadExcluir1.setEnabled(false);
        cFuncionario.funcionario.setCod(0);
        txtCadFunNom.setText("");
        txtCadFunTel.setText("");
        txtCadFunDat.setText("");
        txtCadFunCel.setText("");
        txtCadFunCpf.setText("");
        txtCadFunRg.setText("");
        txtCadFunEma.setText("");
        txtCadFunRua.setText("");
        txtCadFunNum.setText("");
        txtCadFunCep.setText("");
        txtCadFunBai.setText("");
        txtCadFunCid.setText("");
        txtCadFunCom.setText("");
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtCadFunNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadFunNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadFunNumActionPerformed

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked

    }//GEN-LAST:event_btnAlterarMouseClicked

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        cFuncionario.funcionario.setNome(txtCadFunNom.getText());
        cFuncionario.funcionario.setDataNasc((txtCadFunDat.getText()).replace("/", ""));
        cFuncionario.funcionario.setTelefone(cFuncionario.funcionario.retiraCel(txtCadFunTel.getText()));
        cFuncionario.funcionario.setCelular(cFuncionario.funcionario.retiraCel(txtCadFunCel.getText()));
        cFuncionario.funcionario.setCpf(cFuncionario.funcionario.retira(txtCadFunCpf.getText()));
        cFuncionario.funcionario.setRg(cFuncionario.funcionario.retira(txtCadFunRg.getText()));
        cFuncionario.funcionario.setEmail(txtCadFunEma.getText());
        cFuncionario.funcionario.setCep(cFuncionario.funcionario.retira(txtCadFunCep.getText()));
        cFuncionario.funcionario.setRua(txtCadFunRua.getText());
        cFuncionario.funcionario.setNumero(Integer.parseInt(txtCadFunNum.getText()));
        cFuncionario.funcionario.setBairro(txtCadFunBai.getText());
        cFuncionario.funcionario.setCidade(txtCadFunCid.getText());
        cFuncionario.funcionario.setComplemento(txtCadFunCom.getText());
        cFuncionario.funcionario.setEstado(cbCadFunUf.getItemAt(cbCadFunUf.getSelectedIndex()));
        // cFuncionario.funcionario.setObservacao(txtCadFunFunObs.getText());
        if (Validacao.validaCpf(cFuncionario.funcionario.getCep())) {
            if (Validacao.validarEmail(cFuncionario.funcionario.getEmail()) > 0) {
                JOptionPane.showMessageDialog(null, cFuncionario.alterar(cFuncionario.funcionario));
            } else {
                JOptionPane.showMessageDialog(null, "Email não valido");
            }
        } else {
            JOptionPane.showMessageDialog(null, "CPF não valido");
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnDadExcluir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDadExcluir1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDadExcluir1MouseClicked

    private void btnDadExcluir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDadExcluir1ActionPerformed
        // TODO add your handling code here:
        String msg = cFuncionario.apagar(cFuncionario.funcionario);
        JOptionPane.showMessageDialog(null, msg);
    }//GEN-LAST:event_btnDadExcluir1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadCancelar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDadExcluir1;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cbCadFunUf;
    private javax.swing.JComboBox<String> cbPesquisar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public static javax.swing.JTable tbBusca;
    private javax.swing.JTextField txtCadFunBai;
    private javax.swing.JFormattedTextField txtCadFunCel;
    private javax.swing.JFormattedTextField txtCadFunCep;
    private javax.swing.JTextField txtCadFunCid;
    private javax.swing.JTextArea txtCadFunCom;
    private javax.swing.JFormattedTextField txtCadFunCpf;
    private javax.swing.JFormattedTextField txtCadFunDat;
    private javax.swing.JTextField txtCadFunEma;
    private javax.swing.JTextField txtCadFunNom;
    private javax.swing.JTextField txtCadFunNum;
    private javax.swing.JFormattedTextField txtCadFunRg;
    private javax.swing.JTextField txtCadFunRua;
    private javax.swing.JFormattedTextField txtCadFunTel;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
