/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//TELA PRONTA
package VISUAL;

import CONTROLE.CCliente;
import CONTROLE.CMercadoria;
import CONTROLE.CTabela;
import CONTROLE.COrcamento;
import CONTROLE.CValoresServicos;
import MODELO.JavaMailApp;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
//atualizado

/**
 *
 * @author jose
 */
public class TelaGerarOrcamentoCadastro extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaGerarOrcamentoCadastro
     */
    CCliente cCliente;
    CMercadoria cMercadoria;
    CTabela cTabela;
    COrcamento cOrcamento;
    CValoresServicos cValoresServicos;

    public TelaGerarOrcamentoCadastro() {
        initComponents();
        cTabela = new CTabela();
        cCliente = new CCliente();
        cMercadoria = new CMercadoria();
        cOrcamento = new COrcamento();
        txtCadValTot.setEnabled(false);
        lblValMao.setEnabled(false);
        lblValMao.setVisible(false);
        cValoresServicos = new CValoresServicos();
        if ("Administrativo".equals(TelaLogin.tipoUsuario)) {
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
        } else if ("Comum".equals(TelaLogin.tipoUsuario)) {
            btnAlterar.setEnabled(false);
            btnExcluir.setEnabled(false);
        } else {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCadastrar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbBusca = new javax.swing.JTable();
        cbPesquisar = new javax.swing.JComboBox<String>();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCadCli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCadMer = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCadDes = new javax.swing.JTextField();
        txtCadVal = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<String>();
        jLabel9 = new javax.swing.JLabel();
        txtCadValTot = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCadSer = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCadCliOrc = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtCadDat = new javax.swing.JFormattedTextField();
        btnCadMerOrc = new javax.swing.JButton();
        txtCadValMao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblValMao = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        tbBusca.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Nome", "Data", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbBusca.setEditingColumn(0);
        tbBusca.setEditingRow(0);
        tbBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbBuscaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbBusca);

        cbPesquisar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "COD_ORCAMENTO", "NOME", "DATA", " " }));
        cbPesquisar.setToolTipText("");
        cbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPesquisarActionPerformed(evt);
            }
        });

        txtPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisarKeyReleased(evt);
            }
        });

        btnPesquisar.setText("Limpar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel1.setText("Nome do cliente");

        txtCadCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCadCliKeyPressed(evt);
            }
        });

        jLabel2.setText("Mercadoria");

        txtCadMer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadMerActionPerformed(evt);
            }
        });
        txtCadMer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCadMerKeyPressed(evt);
            }
        });

        jLabel6.setText("Valor produtos");

        jLabel5.setText("Descricao ");

        txtCadVal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadValActionPerformed(evt);
            }
        });
        txtCadVal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCadValKeyReleased(evt);
            }
        });

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aguardando aprovacao", "Aprovado", "Reprovado", "Concluido", " " }));

        jLabel9.setText("Status");

        jLabel8.setText("Valor total");

        jLabel3.setText("Servico Solicitado");

        btnCadCliOrc.setText("Buscar");
        btnCadCliOrc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadCliOrcMouseClicked(evt);
            }
        });

        jLabel4.setText("Data");

        try {
            txtCadDat.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnCadMerOrc.setText("Buscar");
        btnCadMerOrc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadMerOrcMouseClicked(evt);
            }
        });
        btnCadMerOrc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadMerOrcActionPerformed(evt);
            }
        });

        txtCadValMao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCadValMaoKeyReleased(evt);
            }
        });

        jLabel7.setText("Mao de obra");

        lblValMao.setText("jLabel10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadMer, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadMerOrc)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadSer))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadCli)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadCliOrc, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadDat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCadVal, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadValMao, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblValMao)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadValTot, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCadDes)
                        .addGap(56, 56, 56)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCadCli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadCliOrc)
                    .addComponent(jLabel4)
                    .addComponent(txtCadDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCadMer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCadMerOrc)
                    .addComponent(jLabel3)
                    .addComponent(txtCadSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCadVal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(txtCadValTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txtCadValMao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblValMao)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCadDes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlterar)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir)
                    .addComponent(btnCadastrar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbBuscaMouseClicked
        // TODO add your handling code here:
        btnAlterar.setEnabled(true);
        btnExcluir.setEnabled(true);
        switch (cTabela.tabela.getTipo()) {
            case 1:
                Object t = tbBusca.getValueAt(tbBusca.getSelectedRow(), 1);
                Object d = tbBusca.getValueAt(tbBusca.getSelectedRow(), 0);
                txtCadCli.setText((String) t);
                cCliente.cliente.setCod((int) d);
                cCliente.buscar(cCliente.cliente);
                break;
            case 2:
                cTabela.tabela.setLin(tbBusca.getSelectedRow());
                int i = Integer.parseInt((tbBusca.getModel()).getValueAt(cTabela.tabela.getLin(), 0).toString());
                cTabela.tabela.setCod(i);
                boolean result;
                cOrcamento.orcamento.setCod(cTabela.tabela.getCod());
                result = cOrcamento.buscar(cOrcamento.orcamento);

                //JOptionPane.showMessageDialog(null, result);
                if (result) {
                    lblValMao.setVisible(true);
                    cCliente.cliente.setCod(cOrcamento.orcamento.getCodCliente());
                    cCliente.buscar(cCliente.cliente);
                    cMercadoria.mercadoria.setCod(cOrcamento.orcamento.getCodMercadoria());
                    cMercadoria.buscar(cMercadoria.mercadoria);
                    cValoresServicos.valoresServicos.setCod(cOrcamento.orcamento.getcodPrestacaoServicos());
                    cValoresServicos.buscar(cValoresServicos.valoresServicos);
                    //  txtCadCod.setText(Integer.toString(cOrcamento.orcamento.getCod()));
                    txtCadCli.setText(cCliente.cliente.getNome());
                    txtCadMer.setText(cMercadoria.mercadoria.getNome());
                    txtCadValMao.setText(cValoresServicos.valoresServicos.getNome());
                    lblValMao.setText(Float.toString(cValoresServicos.valoresServicos.getValorPrestacaoServico()));
                    //JOptionPane.showMessageDialog(null,cOrcamento.orcamento.getTelefone());
                    txtCadSer.setText(cOrcamento.orcamento.getServicoSolicitado());
                    txtCadDes.setText(cOrcamento.orcamento.getDescricaoProblema());
                    String ano = cOrcamento.orcamento.getDataSolicitacao().substring(0, 4);
                    String mes = cOrcamento.orcamento.getDataSolicitacao().substring(5, 7);
                    String dia = cOrcamento.orcamento.getDataSolicitacao().substring(8);
                    cOrcamento.orcamento.setDataSolicitacao(dia + "" + mes + "" + ano);
                    txtCadDat.setText(cOrcamento.orcamento.getDataSolicitacao());
                    txtCadVal.setText(Float.toString(cOrcamento.orcamento.getValorProdutoUtilizado()));
                    txtCadValTot.setText(Float.toString(cOrcamento.orcamento.getValorTotal()));
                    txtCadValTot.setText(Float.toString(((cValoresServicos.valoresServicos.getValorPrestacaoServico())) + (Float.parseFloat(txtCadVal.getText()))));
                    cbStatus.getModel().setSelectedItem(cOrcamento.orcamento.getStatus());
                }
                break;

            case 3:
                Object a = tbBusca.getValueAt(tbBusca.getSelectedRow(), 6);
                Object b = tbBusca.getValueAt(tbBusca.getSelectedRow(), 0);
                txtCadMer.setText((String) a);
                cMercadoria.mercadoria.setCod((int) b);
                cMercadoria.buscar(cMercadoria.mercadoria);
                break;
            case 4:
                Object a1 = tbBusca.getValueAt(tbBusca.getSelectedRow(), 1);
                Object b1 = tbBusca.getValueAt(tbBusca.getSelectedRow(), 0);
                txtCadValMao.setText((String) a1);
                cValoresServicos.valoresServicos.setCod((int) b1);
                cValoresServicos.buscar(cValoresServicos.valoresServicos);
                Float k = cValoresServicos.valoresServicos.getValorPrestacaoServico();
                Float e = Float.parseFloat(txtCadVal.getText());
                k += e;
                txtCadValTot.setText(Float.toString(k));
                lblValMao.setText(Float.toString(cValoresServicos.valoresServicos.getValorPrestacaoServico()));
                lblValMao.setVisible(true);
                break;
            default:
                break;
        }
        //cTabela.tabela.setTipo(0);
    }//GEN-LAST:event_tbBuscaMouseClicked

    private void cbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPesquisarActionPerformed

    private void txtPesquisarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarKeyPressed

    private void txtPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisarKeyReleased
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null, txtPesquisar.getText());
        cTabela.tabela.setTipo(2);
        tbBusca.setModel(DbUtils.resultSetToTableModel(cTabela.pesqOrc("tborcamento", txtPesquisar.getText(), String.valueOf(cbPesquisar.getSelectedItem()))));
        tbBusca.getColumnModel().getColumn(0).setPreferredWidth(50);
        tbBusca.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(3).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(4).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(5).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(6).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(7).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(8).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(9).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(10).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(11).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(12).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(13).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(14).setPreferredWidth(150);
        tbBusca.setAutoCreateRowSorter(true);

    }//GEN-LAST:event_txtPesquisarKeyReleased

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        cOrcamento.orcamento.setCod(0);
        cOrcamento.orcamento.setCodCliente(0);
        cOrcamento.orcamento.setCodMercadoria(0);
        cOrcamento.orcamento.setcodPrestacaoServicos(0);
        cCliente.cliente.setCod(0);
        cMercadoria.mercadoria.setCod(0);
        cValoresServicos.valoresServicos.setCod(0);
        txtCadCli.setText("");
        txtCadMer.setText("");
        txtCadValMao.setText("");
        lblValMao.setText("");
        txtCadSer.setText("");
        txtCadDes.setText("");
        txtCadDat.setText("");
        txtCadVal.setText("");
        txtCadValTot.setText("");
        txtCadValTot.setText("");
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        cOrcamento.orcamento.setCodCliente(cCliente.cliente.getCod());
        cOrcamento.orcamento.setDataSolicitacao((txtCadDat.getText()).replace("/", "-"));
        cOrcamento.orcamento.setCodMercadoria(cMercadoria.mercadoria.getCod());
        cOrcamento.orcamento.setServicoSolicitado(txtCadSer.getText());
        cOrcamento.orcamento.setcodPrestacaoServicos(cValoresServicos.valoresServicos.getCod());
        cOrcamento.orcamento.setValorProdutoUtilizado(Float.parseFloat(txtCadVal.getText()));
        cOrcamento.orcamento.setValorTotal(Float.parseFloat(txtCadValTot.getText()));
        cOrcamento.orcamento.setDescricaoProblema(txtCadDes.getText());
        cOrcamento.orcamento.setStatus(cbStatus.getItemAt(cbStatus.getSelectedIndex()));
        JOptionPane.showMessageDialog(null, cOrcamento.gravar(cOrcamento.orcamento));
        if ("Aguardando aprovacao".equals(cOrcamento.orcamento.getStatus())) {
            String corpo = "Sr." + cCliente.cliente.getNome() + " o orçamento do Sr. referente a manuteção do " + cMercadoria.mercadoria.getNome() + " ficou um custo total de R$ " + cOrcamento.orcamento.getValorTotal() + ". Estou no aguardo para realizar a aprovação do Orcamento.Copie o link no seu navegador para APROVAR seu orçamento www.localhost/cadastrar.php .Obrigado pela Atenção !!!"
                    + " \n\n att.";
            JavaMailApp.enviarEmail(cCliente.cliente.getEmail(), "Aguardando Aprovação do Orçamento: ", corpo);
        } else if ("Concluido".equals(cOrcamento.orcamento.getStatus())) {
            String corpo = "Sr." + cCliente.cliente.getNome() + " o orçamento do Sr. referente a manutenção do(a) " + cMercadoria.mercadoria.getNome() + " ficou um custo total de R$ " + cOrcamento.orcamento.getValorTotal() + ", aguardamos o Sr. para retirada do aparelho. \n\n Att. ";
            JavaMailApp.enviarEmail(cCliente.cliente.getEmail(), "Serviço concluído", corpo);
        }
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void txtCadCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadCliKeyPressed
        // TODO add your handling code here:
        cTabela.tabela.setTipo(1);
        tbBusca.setModel(DbUtils.resultSetToTableModel(cTabela.pesq("tbcliente", txtCadCli.getText(), "NOME")));
        tbBusca.getColumnModel().getColumn(0).setPreferredWidth(75);
        tbBusca.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(3).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(4).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(5).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(6).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(7).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(8).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(9).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(10).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(11).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(12).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(13).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(14).setPreferredWidth(150);
        tbBusca.setAutoCreateRowSorter(true);
    }//GEN-LAST:event_txtCadCliKeyPressed

    private void txtCadMerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadMerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadMerActionPerformed

    private void txtCadMerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadMerKeyPressed
        // TODO add your handling code here:
        cTabela.tabela.setTipo(3);
        tbBusca.setModel(DbUtils.resultSetToTableModel(cTabela.pesqMer("tbmercadoria", txtCadMer.getText(), "NOME")));
        tbBusca.getColumnModel().getColumn(0).setPreferredWidth(75);
        tbBusca.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(3).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(4).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(5).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(6).setPreferredWidth(150);
        tbBusca.setAutoCreateRowSorter(true);
    }//GEN-LAST:event_txtCadMerKeyPressed

    private void btnCadCliOrcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadCliOrcMouseClicked
        // TODO add your handling code here
        TelaClienteCadastro t = new TelaClienteCadastro();
        TelaPrincipal.desktop.add(t);
        t.setVisible(true);

    }//GEN-LAST:event_btnCadCliOrcMouseClicked

    private void btnCadMerOrcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadMerOrcMouseClicked
        // TODO add your handling code here:
        TelaMercadoriaCadastro t = new TelaMercadoriaCadastro();
        TelaPrincipal.desktop.add(t);
        t.setVisible(true);
    }//GEN-LAST:event_btnCadMerOrcMouseClicked

    private void txtCadValActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadValActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadValActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, cOrcamento.apagar(cOrcamento.orcamento));
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        cOrcamento.orcamento.setCodCliente(cCliente.cliente.getCod());
        cOrcamento.orcamento.setDataSolicitacao((txtCadDat.getText()).replace("/", "-"));
        cOrcamento.orcamento.setCodMercadoria(cMercadoria.mercadoria.getCod());
        cOrcamento.orcamento.setServicoSolicitado(txtCadSer.getText());
        cOrcamento.orcamento.setcodPrestacaoServicos(cValoresServicos.valoresServicos.getCod());
        cOrcamento.orcamento.setValorProdutoUtilizado(Float.parseFloat(txtCadVal.getText()));
        cOrcamento.orcamento.setValorTotal(Float.parseFloat(txtCadValTot.getText()));
        cOrcamento.orcamento.setDescricaoProblema(txtCadDes.getText());
        cOrcamento.orcamento.setStatus(cbStatus.getItemAt(cbStatus.getSelectedIndex()));
        JOptionPane.showMessageDialog(null, cOrcamento.alterar(cOrcamento.orcamento));
        if ("Aguardando aprovacao".equals(cOrcamento.orcamento.getStatus())) {
            String corpo = "Sr." + cCliente.cliente.getNome() + " o orçamento do Sr. referente a manuteção do " + cMercadoria.mercadoria.getNome() + " ficou um custo total de R$ " + cOrcamento.orcamento.getValorTotal() + ". Estou no aguardo para realizar a aprovação do Orcamento. Obrigado pela Atenção"
                    + " \n\n att.";
            JavaMailApp.enviarEmail(cCliente.cliente.getEmail(), "Aguardando Aprovação do Orçamento ", corpo);
        } else if ("Concluido".equals(cOrcamento.orcamento.getStatus())) {
            String corpo = "Sr." + cCliente.cliente.getNome() + " o orçamento do Sr. referente a manutenção do(a) " + cMercadoria.mercadoria.getNome() + " ficou um custo total de R$ " + cOrcamento.orcamento.getValorTotal() + ", aguardamos o Sr. para retirada do aparelho. \n\n Att.";
            JavaMailApp.enviarEmail(cCliente.cliente.getEmail(), "Serviço concluído", corpo);
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void txtCadValKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadValKeyReleased
        // TODO add your handling code here:
        Float a = cValoresServicos.valoresServicos.getValorPrestacaoServico();
        Float b = Float.parseFloat(txtCadVal.getText());
        a += b;
        txtCadValTot.setText(Float.toString(a));
    }//GEN-LAST:event_txtCadValKeyReleased

    private void txtCadValMaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCadValMaoKeyReleased
        // TODO add your handling code here:
        cTabela.tabela.setTipo(4);
        tbBusca.setModel(DbUtils.resultSetToTableModel(cTabela.pesq("tbprestacaoservico", txtCadValMao.getText(), "NOME")));
        tbBusca.getColumnModel().getColumn(0).setPreferredWidth(75);
        tbBusca.getColumnModel().getColumn(1).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(2).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(3).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(4).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(5).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(6).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(7).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(8).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(9).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(10).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(11).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(12).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(13).setPreferredWidth(150);
        tbBusca.getColumnModel().getColumn(14).setPreferredWidth(150);
        tbBusca.setAutoCreateRowSorter(true);
    }//GEN-LAST:event_txtCadValMaoKeyReleased

    private void btnCadMerOrcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadMerOrcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCadMerOrcActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCadCliOrc;
    private javax.swing.JButton btnCadMerOrc;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JComboBox<String> cbPesquisar;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblValMao;
    public static javax.swing.JTable tbBusca;
    private javax.swing.JTextField txtCadCli;
    private javax.swing.JFormattedTextField txtCadDat;
    private javax.swing.JTextField txtCadDes;
    private javax.swing.JTextField txtCadMer;
    private javax.swing.JTextField txtCadSer;
    private javax.swing.JTextField txtCadVal;
    private javax.swing.JTextField txtCadValMao;
    private javax.swing.JTextField txtCadValTot;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
